spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
  id: ${BOT_ID}
api:
  key: ${API_KEY}