spring:
  datasource:
    url: <database-url>
    username: <database-username>
    password: <database-password>
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
bot:
  token: <bot-token>
  username: <bot-username>
  id: <bot-id>
api:
  key: <api-key>